creation_rules:
  - path_regex: systems/dex/secrets\.yaml$
    key_groups:
    - age:
      - age1e0sxdpqg20nwypjh9pecastjn2w50ju0qw997muen0j6cctnvcgsr3k494
  - path_regex: systems/downloader/secrets\.yaml$
    key_groups:
    - age:
      - age1xv0f3x672rlpsv90wyh75gvz5g6r6fnfgg5ptg9thggl0k3hufeqlqr0y0
  - path_regex: systems/metabox/secrets\.yaml$
    key_groups:
    - age:
      - age1ukc0u6p74krmpn5nqw7g26s00xmewu84lwrv4ap6kzwsnf3afgms9klvgf
  - path_regex: systems/x/secrets\.yaml$
    key_groups:
    - age:
      - age1wajqarhnwgdvwmd3kz0cqx35nwjg3fpe06hdpyuftj0zprwuy4asspdajv
  - path_regex: systems/ptv/secrets\.yaml$
    key_groups:
    - age:
      - age1e87t0gjlaav3uygyqtasjzgg846d3n6v53t90se79qy82ky2e9ksjrkz0x
