# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "uas"
    "sd_mod"
    "btintel"
    "nvme"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6532b27d-047a-45c8-8da6-7f6259fda267";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."cryptroot".device =
    "/dev/disk/by-uuid/43c46b00-1e99-48a7-8758-d73b3b6bbfe8";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/255E-D838";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  boot.initrd.secrets = {
    "lukskey" = "/root/lukskey";
  };

  fileSystems."/media/media" = {
    device = "/dev/mapper/media";
    fsType = "ext4";
    options = [ "nofail" ];
    encrypted = {
      enable = true;
      label = "media";
      blkDev = "/dev/disk/by-uuid/109d4558-b541-4192-a9db-2fd2864c8b3d";
      keyFile = "/lukskey";
    };
  };
  fileSystems."/media/media2" = {
    device = "/dev/mapper/media2";
    fsType = "ext4";
    options = [ "nofail" ];
    encrypted = {
      enable = true;
      label = "media2";
      blkDev = "/dev/disk/by-uuid/df4e8ff2-7538-44a1-ac79-3da87d456415";
      keyFile = "/lukskey";
    };
  };
  fileSystems."/media/personal" = {
    device = "/dev/mapper/personal";
    fsType = "ext4";
    options = [ "nofail" ];
    encrypted = {
      enable = true;
      label = "personal";
      blkDev = "/dev/disk/by-uuid/dfd9f448-cd9d-4f9f-a1b9-9adcea897582";
      keyFile = "/lukskey";
    };
  };
  fileSystems."/media/backup" = {
    device = "/dev/mapper/backup";
    fsType = "ext4";
    options = [
      "nofail"
      "x-systemd.device-timeout=10"
    ];
    encrypted = {
      enable = true;
      label = "backup";
      blkDev = "/dev/disk/by-uuid/05d74c77-c9f2-4101-af0b-b1c7141a4fd0";
      keyFile = "/lukskey";
    };
  };

  fileSystems."/media/games" = {
    device = "/dev/disk/by-uuid/0BB20EC37670AE62";
    fsType = "ntfs";
    options = [
      "rw"
      "uid=1000"
      "nofail"
    ];
  };

  fileSystems."/d" = {
    device = "/media/media";
    options = [ "bind" ];
  };

  fileSystems."/f" = {
    device = "/media/media2";
    options = [ "bind" ];
  };

  fileSystems."/audiobooks" = {
    device = "/media/media/audiobooks";
    options = [ "bind" ];
  };

  fileSystems."/podcasts" = {
    device = "/media/media/podcasts";
    options = [ "bind" ];
  };

  swapDevices = [ { device = "/.swapfile"; } ];

  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
