# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-intel"
    "iwlwifi"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/bd5f124c-0d5a-4c3b-b4ec-755503b74099";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-e6807611-6e16-4a57-aa19-80e7efd2ec72".device =
    "/dev/disk/by-uuid/e6807611-6e16-4a57-aa19-80e7efd2ec72";

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/2FAC-32E0";
    fsType = "vfat";
  };

  fileSystems."/media/media" = {
    device = "//10.10.0.123/media";
    fsType = "cifs";
    options = [
      "uid=1000,gid=100,x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s,credentials=/etc/nixos/smb-secrets"
    ];
  };
  fileSystems."/media/media2" = {
    device = "//10.10.0.123/media2";
    fsType = "cifs";
    options = [
      "uid=1000,gid=100,x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s,credentials=/etc/nixos/smb-secrets"
    ];
  };
  fileSystems."/media/personal" = {
    device = "//10.10.0.123/personal";
    fsType = "cifs";
    options = [
      "uid=1000,gid=100,x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s,credentials=/etc/nixos/smb-secrets"
    ];
  };
  fileSystems."/media/games" = {
    device = "//10.10.0.123/games";
    fsType = "cifs";
    options = [
      "uid=1000,gid=100,x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s,credentials=/etc/nixos/smb-secrets"
    ];
  };

  swapDevices = [
    {
      device = "/.swapfile";
      size = 2048;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
