gen:
  file: ~/.config/chordgen/chords.csv
  keyboard:
    directional:
      custom_layout:
      - _X__X__X__X__X__X__X__X_
      - X_XX_XX_XX_XX_XX_XX_XX_X
      - _X__X__X__X__X__X__X__X_
      - _X__X_
      - X_XX_X
      - _X__X_
      - _X__X_
      - X_XX_X
      - _X__X_
      directional_change_penalty: 2
      effort_map:
      - '040030020020'
      - '695594493493'
      - '030020010010'
      - '030'
      - '192'
      - '040'
      - '030'
      - '192'
      - '040'
      layout: charachorder
    standard:
      custom_layout:
      - _byou'"ldvw_
      - _ciea,.htsn_
      - _gxjk-?rmfp_
      - ____
      effort_map:
      - '965447'
      - '732116'
      - '865536'
      - '43'
      layout: custom
      same_column_chord_penalty: 2
      same_row_chord_penalty: 2
      scissor_penalty: 3
    type: standard
  min_chord_length: 0
  min_word_length: 3
  overwrite_alts: false
output:
  charachorder:
    file: ~/.config/chordgen/charachorder_chords.json
  formats:
  - qmk
  - zmk
  - charachorder
  - kanata
  - training
  kanata:
    alt1_keys:
    - lalt
    alt2_keys:
    - spc
    alt3_keys:
    - lalt
    - spc
    chord_keys:
    - prtsc
    chord_timeout: 100
    file: ~/nix/keymaps/kanata/chords.kbd
    key_mapping:
      a: d
      b: tab
      c: caps
      d: o
      e: s
      f: /
      g: lsft
      h: k
      i: a
      j: x
      k: c
      l: i
      m: .
      n: ''''
      o: w
      p: rsft
      r: ','
      s: ;
      t: l
      u: e
      v: '['
      w: p
      x: z
      y: q
    limit: 0
    shifted_chord_keys:
    - prtsc
    - ralt
  qmk:
    alt1_keys:
    - KC_CHORD_ALT1
    alt2_keys:
    - KC_CHORD_ALT2
    alt3_keys:
    - KC_CHORD_ALT1
    - KC_CHORD_ALT2
    chord_keys:
    - KC_CHORD
    file: ~/.config/chordgen/qmk_chords.def
    key_codes:
      A: KC_CTL_A
      C: KC_SFT_C
      E: KC_GUI_E
      H: KC_CTL_H
      I: KC_ALT_I
      J: KC_CAG_J
      M: KC_CAG_M
      N: KC_SFT_N
      S: KC_ALT_S
      T: KC_GUI_T
    shifted_chord_keys:
    - KC_CHORD
    - KC_CHORD_SFT
  training:
    file: ~/.config/chordgen/training.txt
  zmk:
    alt1_keys:
    - '!'
    alt2_keys:
    - '@'
    alt3_keys:
    - '!'
    - '@'
    chord_keys:
    - $
    chord_timeout: 100
    chords_file: ~/.config/chordgen/zmk_chords.dtsi
    key_positions:
    - _qwertyuiop_
    - _asdfghjkl;_
    - _zxcvbnm,./_
    - _!@#$_
    limit: 0
    macros_file: ~/.config/chordgen/zmk_macros.dtsi
    shifted_chord_keys:
    - $
    - '#'
